#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DartScorer.Droid.Resource", IsApplication=true)]

namespace DartScorer.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int legs_per_set_array = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int sets_array = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int start_score_array = 2131034114;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int game_on_button = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int legs_per_set_chosen = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int legs_per_set_spinner = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int myButton = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int player1_text_edit = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int player2_text_edit = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int sets_chosen = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int sets_spinner = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int start_score_chosen = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int start_score_spinner = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int textView = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MatchSetUp = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int enter_score = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int game_on = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int game_shot = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int leg_score = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int legs_per_set = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int player_1 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int player_2 = 2130968582;
			
			// aapt resource value: 0x7f04000c
			public const int set_score = 2130968588;
			
			// aapt resource value: 0x7f040002
			public const int sets = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int start_score = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int thrower = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
